name: canshield
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - hydra-core
  - numpy
  - pandas
  - seaborn
  - tqdm
  - pip:
    - keras==2.10.0
    - tensorflow==2.10.0
    - scikit-learn